apiVersion: appstudio.redhat.com/v1alpha1
kind: IntegrationTestScenario
metadata:
  name: enterprise-contract
spec:
  application: policy-contract-enforce
  bundle: quay.io/hacbs-contract/ec-task-bundle@sha256:68f8aac6b9c5ed5c2ccee67446b484155a2ea66969baaa0c3d872e5d0a71fa18
  contexts:
  - description: EC testing
    name: application
  pipeline: enterprise-contract
  params:
    - name: POLICY_CONFIGURATION
      value: ec-policy