apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  name: ec-policy
spec:
  configuration: 
    collections:
    - minimal
  description: My EnterpriseContractPolicy
  publicKey: |-
    -----BEGIN PUBLIC KEY-----
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEWVUppvU1x8t866CQQSXbKpojoaTq
    imMnVnZ31e2ubZHKL1LdfgPG2gHIPeSeouTa8upOz9W+xxBFnA0X515Nsw==
    -----END PUBLIC KEY-----
  sources:
  - data:
    - oci::https://quay.io/hacbs-contract/ec-policy-data:latest
    name: Default Policies
    policy:
    - oci::https://quay.io/hacbs-contract/ec-release-policy:latest